### ISSUE TITLE
crash - /stopsound

### ISSUE THREAD

**Issue by YasinKalca** [xqwtxon/PlaySound#2]
**[13:06:38.901] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\player\Player::dataPacket()" (EXCEPTION) in "plugins/PlaySound_dev-7.phar/src/xqwtxon/PlaySound/StopSoundCommand" at line 68**

happens once executing /stopsound

**Comment by xRodzMC** [comment]
Fixed in #4
